= FLIF16 Specification
Jon Sneyers <jon@cloudinary.com>; other contributors: add yourself here
Work in progress
:toc: right
:icons: font
:source-highlighter: coderay
:homepage: http://flif.info

The Free Lossless Image Format (FLIF) is a lossless image compression format.
It supports grayscale, RGB and RGBA, with a color depth from 1 to 16 bits per channel.

This document specifies the FLIF16 bitstream, as implemented by version 0.2 of the reference encoder (https://github.com/FLIF-hub/FLIF), which was released in September 2016.

== Overview of the format

A FLIF file consists of 4 parts, with increasingly complicated encoding methods:

1. The main header, containing basic image metadata: width, height, color depth, number of frames. This information is encoded in a straightforward way, to make it easy to quickly identify a file.
2. Optional metadata chunks. These chunks contain non-pixel data: Exif/XMP metadata, an ICC color profile, ... This information is encoded using DEFLATE compression.
3. Second header, containing further information about how the actual pixel data is encoded. This header also describes a chain of transformations that were applied before encoding, which have to be reversed after decoding (e.g. the YCoCg color transform). This information is encoded using CABAC entropy coding.
4. The actual pixel data. This information is encoded using MANIAC entropy coding.


include::parts/part1.adoc[]

include::parts/part2.adoc[]

include::parts/symbol.adoc[]

include::parts/part3.adoc[]

include::parts/maniac.adoc[]

include::parts/part4.adoc[]

