
== Part 3: second header

From here on, all values are encoded using arithmetic coding.

rac24(_min_,_max_) denotes an integer in the interval _min_.._max_ (inclusive), encoded using the UniformSymbolCoder and a 24-bit RAC. This encoding is not context-adaptive, and every number in the interval gets a fixed chance (close to a uniform distribution, hence the name).
rac24(_b_) denotes an integer of _b_ bits, i.e. it's a synonym for rac24(0,2^_b_-1).

rac24_CONTEXT(_min_,_max_) denotes an integer in the interval _min_.._max_ (inclusive), encoded using the SimpleSymbolCoder and a 24-bit RAC, where the chance table is given by CONTEXT. This encoding is context-adaptive; numbers are encoded using a zero-sign-exponent-mantissa representation, which favors distributions in which near-zero values have a higher chance.

|===
| Type | Description | Condition | Default value

| 1 byte
| NUL byte (`"\0"`)
|
|

| rac24(1,16)
| Bits per pixel of the channels
| **Bpc** == '0': repeat(**nb_channels**)
| 8 if **Bpc** == '1', 16 if **Bpc** == '2'

| rac24(0,1)
| Flag: **alpha_zero**
| **nb_channels** > 3
| 0

| rac24(0,100)
| Number of loops
| **nb_frames** > 1
|

| rac24(0,60_000)
| Frame delay in ms
| **nb_frames** > 1: repeat(**nb_frames**)
|

| rac24(0,1)
| Flag: **has_custom_cutoff_and_alpha**
|
|

| rac24(1,128)
| **cutoff**
| **has_custom_cutoff_and_alpha**
| 2

| rac24(2,128)
| **alpha divisor**
| **has_custom_cutoff_and_alpha**
| 19

| rac24(0,1)
| Flag: **has_custom_bitchance**
| **has_custom_cutoff_and_alpha**
| 0

| ?
| Bitchance
| **has_custom_bitchance**
|

| variable
| Transformations (see below)
|
|

| rac24(1) = 0
| Indicator bit: done with transformations
|
|

| rac24(0,2)
| Invisible pixel predictor
| **alpha_zero** && interlaced && alpha range includes zero
|
|===

Channels are ordered as follows:

|===
| Channel number | Description

| 0              | Red or Gray
| 1              | Green
| 2              | Blue
| 3              | Alpha
|===


=== Transformations

|===
| Type             | Description

| rac24(1) = 1     | Indicator bit: not done yet
| rac24(0,13)      | Transformation identifier
| variable         | Transformation data (depends on transformation)
|===

Transformations have to be encoded in ascending order of transformation identifier. All transformations are optional.

Transformations serve two main purposes:

1. to modify the pixel data (in a reversible way) to make it compress better, and
2. to keep track of the range of actually occuring pixel values, in order to narrow it down.

Initially, pixel values are assumed to be in the range 0..2^(bit_depth); this range can be modified by transformations.
We'll use **range(_channel_).min** and **range(_channel_).max** to denote the global minimum and maximum value of a particular channel. We also use a potentially more accurate (narrow) conditional range **crange(_channel_,_values_)** to denote the range of a pixel value in channel **_channel_**, _given that the pixel values in previously encoded channels are_ **_values_**. Initially, the conditional ranges are simply equal to the global range, but transformations might change that.

As a typical example, consider 8-bit RGBA to which the YCoCg transformation gets applied:

|===
| Channel number | Original meaning | Original range | New meaning        | New range

| 0              | Red              | 0..255         | Luma (Y)           | 0..255
| 1              | Green            | 0..255         | Chroma orange (Co) | -255..255
| 2              | Blue             | 0..255         | Chroma green (Cg)  | -255..255
| 3              | Alpha            | 0..255         | Alpha              | 0..255
|===

In this example, the conditional ranges also change: e.g. **crange(1,2)** (the range for Co given that Y=2) happens to be -7..7.


==== Transformation 0: ChannelCompact
==== Transformation 1: YCoCg
==== Transformation 2: reserved (unused)
==== Transformation 3: PermutePlanes
==== Transformation 4: Bounds
==== Transformation 5: PaletteAlpha
==== Transformation 6: Palette
==== Transformation 7: ColorBuckets
==== Transformation 8: reserved (unused)
==== Transformation 9: reserved (unused)
==== Transformation 10: DuplicateFrame
==== Transformation 11: FrameShape
==== Transformation 12: FrameLookback
==== Transformation 13: reserved (unused)


