
== Part 3: second header


|===
| Type | Description | Condition | Default value

| 1 byte
| NUL byte (0x00), chunk name of a FLIF16 bitstream
|
|

| uni_int(1,16)
| Bits per pixel of the channels
| **Bpc** == '0': repeat(**nb_channels**)
| 8 if **Bpc** == '1', 16 if **Bpc** == '2'

| uni_int(0,1)
| Flag: **alpha_zero**
| **nb_channels** > 3
| 0

| uni_int(0,100)
| Number of loops
| **nb_frames** > 1
|

| uni_int(0,60_000)
| Frame delay in ms
| **nb_frames** > 1: repeat(**nb_frames**)
|

| uni_int(0,1)
| Flag: **has_custom_cutoff_and_alpha**
|
|

| uni_int(1,128)
| **cutoff**
| **has_custom_cutoff_and_alpha**
| 2

| uni_int(2,128)
| **alpha divisor**
| **has_custom_cutoff_and_alpha**
| 19

| uni_int(0,1)
| Flag: **has_custom_bitchance**
| **has_custom_cutoff_and_alpha**
| 0

| ?
| Bitchance
| **has_custom_bitchance**
|

| variable
| Transformations (see below)
|
|

| uni_int(1) = 0
| Indicator bit: done with transformations
|
|

| uni_int(0,2)
| Invisible pixel predictor
| **alpha_zero** && interlaced && alpha range includes zero
|
|===

Channels are ordered as follows:

|===
| Channel number | Description

| 0              | Red or Gray
| 1              | Green
| 2              | Blue
| 3              | Alpha
|===


=== Transformations

For each transformation:

|===
| Type             | Description

| uni_int(1) = 1   | Indicator bit: not done yet
| uni_int(0,13)    | Transformation identifier
| variable         | Transformation data (depends on transformation)
|===

Transformations have to be encoded in ascending order of transformation identifier. All transformations are optional.

Transformations serve two main purposes:

1. to modify the pixel data (in a reversible way) to make it compress better, and
2. to keep track of the range of actually occuring pixel values, in order to narrow it down.

Initially, pixel values are assumed to be in the range 0..2^(bit_depth); this range can be modified by transformations.
We'll use **range(_channel_).min** and **range(_channel_).max** to denote the global minimum and maximum value of a particular channel.

We also use a potentially more accurate (narrow) conditional range **crange(_channel_,_values_)** to denote
the range of a pixel value in channel **_channel_**, _given that the pixel values in previously encoded channels are_ **_values_**.
Initially, the conditional ranges are simply equal to the global range, but transformations might change that.

Finally, we define a function **snap(_channel_,_values_,_x_)** which given a pixel value **_x_** for channel **_channel_**
and pixel values **_values_** in previously encoded channels, returns a 'valid' value as close as possible to **_x_**.
Usually, **snap(_channel_,_values_,_x_)** simply clamps **_x_** to the conditional range **crange(_channel_,_values_)**,
but the ColorBuckets transformation changes that behavior.

.Example
****
As a typical example, consider 8-bit RGBA to which the YCoCg transformation gets applied:

|===
| Channel number | Original meaning | Original range | New meaning        | New range

| 0              | Red              | 0..255         | Luma (Y)           | 0..255
| 1              | Green            | 0..255         | Chroma orange (Co) | -255..255
| 2              | Blue             | 0..255         | Chroma green (Cg)  | -255..255
| 3              | Alpha            | 0..255         | Alpha              | 0..255
|===

In this example, the conditional ranges also change: e.g. **crange(1,2)** (the range for Co given that Y=2) happens to be -7..7.
****

In the following descriptions of transformations, we use **orig_range**, **orig_crange**, **orig_snap** to denote
the original ranges and snap function (the initial ones, or the ones resulting from the previous transformation in the chain).
We use **new_range**, **new_crange**, **new_snap** to denote the updated ranges and snap function.

In part 4 we will use **range**, **crange** and **snap** to denote the final ranges and snap functions, i.e. after applying all
transformations.


include::transformations.adoc[]
