
== Part 4: pixel data

=== Non-Interlaced method

If this encode method is used, then we start immediately with the encoding of the MANIAC trees (see below), followed by the encoding of the pixels. The order in which the pixels are encoded is described by the following nested loops:

* For all channels: (in the order 4,3,0,1,2, skipping those that don't exist or have a singleton range)
** For all rows: (from 0 to **height**-1) :
*** For all frames: (from 0 to **nb_frames**-1) :
**** For all columns: (from 0 to **width**-1, or in case FrameShape is used, from begin[row] to end[row])
***** Encode a pixel

=== Interlaced method

For interlacing, we define the notion of _zoomlevels_. Zoomlevel 0 is the full image. Zoomlevel 1 are all the even-numbered rows of the image (counting from 0). Zoomlevel 2 are all the even-numbered columns of zoomlevel 1. In general: zoomlevel _2k+1_ are all the even-numbered rows of zoomlevel _2k_, and zoomlevel _2k+2_ are all the even-numbered columns of zoomlevel _2k+1_.

In other words, every even-numbered zoomlevel _2k_ is a downsampled version of the image, at scale 1:__2^k__.

We defined the 'maximum zoomlevel' **max_zl** of an image as the zoomlevel with the lowest number that consists of a single pixel. This is always the pixel in the top-left corner of the image (row 0, column 0). This pixel is always encoded first.

The zoomlevels are encoded from highest (most zoomed out) to lowest; in each zoomlevel, obviously only those pixels are encoded that haven't been encoded previously. So in an even-numbered zoomlevel, the odd-numbered rows are encoded, while in an odd-numbered zoomlevel, the odd-numbered columns are encoded.

If the interlaced encode method is used, we do not encode the MANIAC trees right away. Instead, we initialize the trees to a single root node per channel, and start encoding a 'rough preview' of the image (a few of the highest zoomlevels).
This allows a rough thumbnail extraction without needing to decode the MANIAC tree.
Then the MANIAC tree is encoded, and then the rest of the zoomlevels are encoded.


|===
| Type                                         | Description

| rac24(0..**max_zl**)                         | Number of the first MANIAC-encoded zoomlevel: **first_zl**
| Encode_zoomlevels(**max_zl**,**first_zl**+1) | encoding of zoomlevels **max_zl** until **first_zl**+1
| encoding of MANIAC trees                     | see further below
| Encode_zoomlevels(**first_zl**,0)            | encoding of zoomlevels **first_zl** until 0
|===

The encoding of a series of zoomlevels happens by interleaving the channels in some way. This interleaving is either in the 'default order', or in a custom order. In any case, the following invariants must hold:

* Zoomlevel _k_ of a channel can only be encoded after zoomlevel _k+1_ of that channel has already been encoded;
* If channel 3 exists and **alpha_zero** is true, then zoomlevel _k_ of channel 0 (usually Luma) can only be encoded after zoomlevel _k_ of channel 3 (Alpha) has already been encoded;
* Zoomlevel _k_ of channel 1 (usually Co) can only be encoded after zoomlevel _k_ of channel 0 (usually Luma) has been encoded;
* Zoomlevel _k_ of channel 2 (usually Cg) can only be encoded after zoomlevel _k_ of channels 0 and 1 (Luma and Co) have been encoded;
* If channel 4 (FrameLookback) exists: zoomlevel _k_ of any other channel (0,1,2, or 3) can only be encoded after zoomlevel _k_ of channel 4 has already been encoded.

==== Encode_zoomlevels(h,l)

|===
| Type                       | Description                        | Condition

| rac24(0,1)                 | Boolean: **default_order**         |
| rac24(-1,2)                | Pixel predictors **pred[channel]** | repeat(**nb_channels**)
|===

Repeat ** nb_channels * (h-l+1) ** times: (so once for every channel/zoomlevel)

|===
| Type | Description | Condition | Default value

| rac24(0,**nb_channels**-1)
| Channel **c** to be encoded
| not **default_order**
| given by default order

|
| Zoomlevel **z** is implicit
|
|

| rac24(0,2)
| Pixel predictor **p** to use
| **pred[c]** == -1
| **pred[c]**

| Encode_zl(**c**,**z**,**p**)
| Encoding of the next zoomlevel of channel **c**
| **range(c).min < range(c).max** 
|
|===

=== Pixel encoding

==== Pixel predictors
==== Properties
==== Actual pixel encoding


=== MANIAC tree encoding
There is one tree per non-trivial channel (a channel is trivial if its range is a singleton or if it doesn't exist).
The trees are encoded independently and in a recursive (depth-first) way, as follows:

**nb_properties** depends on the channel, the number of channels, and the encoding method (interlaced or non-interlaced).

|===
| Type | Description | Condition

| rac24_A(0,**nb_properties**)
| 0=leaf node, > 0: _property_+1
|

| rac24_B(1,512)
| node counter
| not a leaf node

| rac24_C(range[_property_].min,range[_property_].max-1)
| _test_value_
| not a leaf node

| recursive encoding of left branch
| where range[_property_].min = _test_value_+1
| not a leaf node

| recursive encoding of right branch
| where range[_property_].max = _test_value_
| not a leaf node
|===

=== Checksum

|===
| Type             | Description                       | Condition

| rac24(1)         | Boolean: **have_checksum**            |
| rac24(16)        | Most significant 16 bits of checksum  | **have_checksum**
| rac24(16)        | Least significant 16 bits of checksum | **have_checksum**
|===
