
== Part 2: metadata

Chunks are defined similar to PNG chunks, except the chunk size is encoded with a variable number of bytes, and there is no chunk CRC.
Also, the first chunk (which is always "FLIF") has no explicit chunk size and is not DEFLATE-compressed.

Chunk names are either 4 letters (4 bytes), indicating an optional chunk, or 1 byte with a value below 32, indicating a non-optional chunk.

The convention of using upper and lower case letters is kept, but the meaning of the bits is slightly different.

- First letter: uppercase=critical, lowercase=non-critical -> non-critical chunks can be stripped while keeping a valid file (it might be rendered differently though)
- Second letter: uppercase=public, lowercase=private
- Third letter: uppercase=needed to correctly display the image (e.g. a color profile), lowercase=can be stripped safely without changing anything visually
- Fourth letter: uppercase=safe to copy blindly (when editing the actual image data), lowercase=may depend on image data (e.g. contain a thumbnail)

This optional part is a concatenation of chunks that each look like this:

|===
| Type             | Description

| 4 bytes          | Chunk name
| varint           | Chunk length (_size_)
| _size_ bytes     | DEFLATE-compressed chunk content
|===


The optional chunks are followed by one non-optional chunk with a single-byte chunk name.
Non-optional chunks do not have an explicit chunk size and their content is not DEFLATE-compressed.
Currently the only non-optional chunk has name 0x00 (a NUL byte), which indicates a FLIF16 bitstream.
Future (non-backwards compatible) revisions of the FLIF format will use a different name for this non-optional chunk.

If a decoder encounters an unknown optional chunk, it should proceed decoding (optionally it can produce a warning),
as long as the chunk is non-critical.
If a decoder encounters an unknown non-optional chunk, it should fail and produce an error message.

The following optional chunks are defined:

|===
| Chunk name      | Description           | Content (after DEFLATE-decompression)

| iCCP            | ICC color profile     | raw ICC color profile data
| eXif            | Exif metadata         | `"Exif\0\0"` header followed immediately by a TIFF header and the EXIF data
| eXmp            | XMP metadata          | XMP contained within a read-only xpacket with no padding
|===
