
=== Transformation 0: ChannelCompact

The ChannelCompact transformation looks at each channel independently, and reduces its range
by eliminating values that do not actually occur in the image.

To be able to reconstruct the original values, the mapping from the reduced range to the original
range is encoded. Near-zero symbol coding is used, with a single context which we'll call A.

The information is encoded as follows:

* For each channel **c** :
** **new_range(c).max** = nz_int_A(0,**orig_range(c).max**-**orig_range(c).max**)
** **min** = **orig_range(c).min**
** For **i** = 0..**new_range(c).max**-1 :
*** **decompacted(i)** = **min** + nz_int_A(0, **orig_range(c).max**-**min**+**new_range(c).max**-**i**)
*** **min** = **decompacted(i)**+1

The effect of this transformation is as follows:

* **new_range(c).min = new_crange(c,...).min = 0**
* **new_range(c).max = new_crange(c,...).max** is explicitly encoded
* **new_snap** is the default snap function (simple clamping)

To reverse the transformation (after decoding the pixel values) :

* For each channel **c** :
** For every pixel value **v** :
*** Set **v** = **decompacted(v)**



=== Transformation 1: YCoCg

The YCoCg transformation converts the colorspace from RGB to YCoCg.
No information has to be encoded for this (besides the identifier of the transformation).

The transformation only affects the first three channels (0,1,2).
It is not allowed to be used if **nb_channels** = 1.


==== Pixel transformation

|===
| Channel  | Original meaning | New meaning        | Forward transform        | Reverse transform

| 0        | Red \(R)         | Luma (Y)           | Y = (((R+B)>>1) + G)>>1  | R = Co + Y + ((1-Cg)>>1) - (Co>>1)
| 1        | Green (G)        | Chroma orange (Co) | Co = R - B               | G = Y - ((-Cg)>>1)
| 2        | Blue (B)         | Chroma green (Cg)  | Cg = G - ((R+B)>>1)      | B = Y + ((1-Cg)>>1) - (Co>>1)
|===

Luma (Y) corresponds to roughly 50% green, 25% red, 25% blue. Chroma orange (Co) is positive for colors near orange (red, orange, yellow),
and negative for colors near blue. Chroma green (Cg) is positive for colors near green and negative for colors near purple.

NOTE: The YCoCg transformation tends to decorrelate the channels, which helps to improve compression.
For example, for grayscale images, i.e. images where R=G=B, the result of the YCoCg transform is Y=R (=G=B), Co=Cg=0.
Human perception is more sensitive to luma than it is to chroma. For this reason, in interlaced mode,
the default zoomlevel/channel ordering (see below) gives priority to the luma channel; this results in
partial decodes (progressive previews) which are effectively chroma subsampled.


==== New ranges

Define _origmax4_ to be equal to max(**orig_range(0).max**,**orig_range(1).max**,**orig_range(2).max**)/4+1
and _newmax_ to be equal to 4 * (_origmax4_) - 1.
In the most common case where the three channels have the range 0..255, this evaluates to _origmax4_ = 64 and _newmax_ = 255.

|===
| Channel number **c** | Original meaning | New meaning        | **new_range(c)**

| 0                    | Red \(R)         | Luma (Y)           | 0.._newmax_
| 1                    | Green (G)        | Chroma orange (Co) | -_newmax_.._newmax_
| 2                    | Blue (B)         | Chroma green (Cg)  | -_newmax_.._newmax_
|===


Unlike the RGB color space, not every coordinate in the YCoCg color space corresponds
to an actual color. In particular, the range for Co and Cg is much smaller for near-black and
near-white colors than for intermediate luma values:

video::-v-xoKZBnhI[youtube,opts="modest",width=512,height=512]
(Download the above animation losslessly:
link:illustrations/YCoCg.webp[WebP (847K)],
link:illustrations/YCoCg.apng[APNG (938K)],
link:illustrations/YCoCg.flif[FLIF (90K)];
or lossy:
link:illustrations/YCoCg.gif[GIF (7024K)],
link:illustrations/YCoCg.mp4[MP4 (235K)])


The conditional range function **crange** is updated to reflect this.
It is updated as follows:

* **new_crange(0)** = **new_range(0)**
* **new_crange(1,_yval_).min** =
[horizontal]
 -3 + 4 * _yval_        :: if _yval_ < _origmax4_ - 1
 4 * (_yval_-_newmax_)  :: if _yval_ > 3 * _origmax4_ - 1
 -_newmax_              :: otherwise
* **new_crange(1,_yval_).max** =
[horizontal]
 3 + 4 * _yval_         :: if _yval_ < _origmax4_ - 1
 4 * (_newmax_-_yval_)  :: if _yval_ > 3 * _origmax4_ - 1
 _newmax_               :: otherwise
* **new_crange(2,_yval_,_coval_).min** =
[horizontal]
 -2 - 2 * _yval_        :: if _yval_ < _origmax4_ - 1
 -2 * (_newmax_-_yval_) + 2 * ((abs(_coval_)+1)/2)  :: if _yval_ > 3 * _origmax4_ - 1
 min(2 * _yval_ + 1, 2 * _newmax_ - 2 * _yval_ - 2 * ((abs(_coval_)+1)/2))      :: otherwise
* **new_crange(2,_yval_,_coval_).max** =
[horizontal]
 1 + 2 * _yval_ - 2 * (abs(_coval_)/2)        :: if _yval_ < _origmax4_ - 1
 2 * (_newmax_-_yval_)                        :: if _yval_ > 3 * _origmax4_ - 1
 min(2 * (_yval_- _newmax_), - 2 * _yval_ - 1 + 2* (abs(_coval_)/2))            :: otherwise


[discrete]
=== Transformation 2: reserved (unused)

Transformation identifier 2 is not used. It is reserved for future extensions that support transformations
to other color spaces like YCbCr.

=== Transformation 3: PermutePlanes

The PermutePlanes transformation reorders (permutes) the channels; optionally it also subtracts the values of the new channel 0
from the values of channels 1 and 2. This transformation is useful if for some reason the YCoCg transformation is not used:
it can e.g. be used to transform RGB to G (R-G) (B-G).

This transformation is not allowed to be used in conjunction with the YCoCg transformation; it is also not allowed to be used if **nb_channels** = 1. Also, if **alpha_zero** is true, then channel 3 (Alpha) is not allowed to be permuted to a different channel number.

There are two main reasons to do a channel reordering: better compression (the order matters for compression since the values of previously encoded channels are used in the MANIAC properties, see below), and better progressive previews (e.g. Green is perceptually more important than Red and Blue, so it makes sense to encode it first). Additionally, subtracting channel 0 from the other channels is a simple form of channel decorrelation; usually not as good as the YCoCg transformation though.

We denote the permutation used by PermutePlanes with **p**, where **p(nc)=oc** means that the new channel number **nc** corresponds to the old channel number **oc**.

Without subtraction, the forward transformation looks as follows:

|===
| Channel number **c** | Original pixel value | New pixel value (no Subtract) | **new_range(c)** (no Subtract)

| 0                    | _v~0~_         | _v~**p(0)**~_   | **orig_range(p(0))**
| 1                    | _v~1~_         | _v~**p(1)**~_   | **orig_range(p(1))**
| 2                    | _v~2~_         | _v~**p(2)**~_   | **orig_range(p(2))**
| 3                    | _v~3~_         | _v~**p(3)**~_   | **orig_range(p(3))**
|===

With subtraction, the forward transformation looks as follows:

|===
| Channel number **c** | Original pixel value | New pixel value (with Subtract) | **new_range(c)** (with Subtract)

| 0                    | _v~0~_         | _v~**p(0)**~_   | **orig_range(p(0))**
| 1                    | _v~1~_         | _v~**p(1)**~_-_v~**p(0)**~_   | **orig_range(p(1)).min**-**orig_range(p(0)).max** to **orig_range(p(1)).max**-**orig_range(p(0)).min**

| 2                    | _v~2~_         | _v~**p(2)**~_-_v~**p(0)**~_   | **orig_range(p(2)).min**-**orig_range(p(0)).max** to **orig_range(p(2)).max**-**orig_range(p(0)).min**
| 3                    | _v~3~_         | _v~**p(3)**~_   | **orig_range(perm(3))**
|===

The reverse transformation can easily be derived from this: given input values __(in~0~,in~1~,in~2~,in~3~)__, the output values are given by __out~**p(c)**~ = in~**c**~__ if there is no Subtract or **c** is 0 or 3, and by
__out~**p(c)**~ = in~**c**~ + in~0~__ if there is Subtract and **c** is 1 or 2.

To encode the parameters of this transformation, near-zero symbol coding is used, with a single context which we will call A.

|===
| Type | Description | Condition

| nz_int_A(0,1)
| Boolean: **Subtract**
|

| nz_int_A(0,**nb_channels**-1)
| **p(c)**
| repeat: **c** from 0 to **nb_channels**-1
|===

The decoder has to check that **p** actually describes a permutation, i.e. it is a bijection (no two input channels map to the same output channel).


=== Transformation 4: Bounds
=== Transformation 5: PaletteAlpha
=== Transformation 6: Palette
=== Transformation 7: ColorBuckets

The ColorBuckets transformation is an alternative to the Palette transformations; it is useful for sparse-color images, especially if the number of colors is relatively small but still too large for effective palette encoding.

Unlike the Palette transformations, ColorBuckets does not modify the actual pixel values. As a result, the reverse transformation is trivial: nothing has to be done. However, the transformation does change the *crange* and the *snap* functions. By reducing the range of valid pixel values (sometimes drastically), compression improves.

A 'Color Bucket' is a (possibly empty) set of pixel values. For channel 0, there is a single Color Bucket *b~0~*. For channel 1, there is one Color Bucket for each pixel value in **orig_range(0)**; we'll denote these Color Buckets with **b~1~(v~0~)**. For channel 2, there is one Color Bucket for each combination of values (**v~0~**,**Q(v~1~)**) where **v~0~** is in **orig_range(0)**, **v~1~** is in **orig_range(1)**, and the quantization function **Q** maps *x* to (**x** - **orig_range(1).min**) / 4. Finally, for channel 3, there is a single Color Bucket **b~3~**.

The new ranges are identical to the original ranges: **new_range(c)** = **orig_range(c)**.

The new _conditional_ ranges are given by the minimum and maximum of the corresponding Color Buckets:

* **new_crange(0)** = min(**b~0~**) .. max(**b~0~**)
* **new_crange(1,v~0~)** = min(**b~1~(v~0~)**) .. max(**b~1~(v~0~)**)
* **new_crange(2,v~0~,v~1~)** = min(**b~2~(v~0~,Q(v~1~)**) .. max(**b~2~(v~0~,Q(v~1~)**)
* **new_crange(3)** = min(**b~3~**) .. max(**b~3~**)

The new *snap* function returns the value in the corresponding Color Bucket that is _closest_ to the input value;
if there are two such values, it returns the lowest one. For example, if Color Bucket **b~1~(20)** is the set {-1,3,4,6,8},
then **new_snap(1,20,x)** returns -1 for *x*=-100, 4 for *x*=5, 6 for *x*=6, and 8 for *x*=100.

The ColorBuckets transformation is not allowed in the following circumstances:

* Palette or PaletteAlpha is used, or in general, both channel 0 and 2 contain only zeroes: **orig_range(0)** = **orig_range(2)** = 0 .. 0
* The image is a grayscale image
* Channel 1 is trivial: **orig_range(1)** is a singleton
* Channel 0, 1 or 2 requires more than 10 bits: **orig_range(c).max** - **orig_range(c).min** > 1023


To encode the Color Buckets, (generalized) near-zero symbol coding is used with 6 different contexts, which we will call A,B,C,D,E, and F.  The encoding is quite complicated.

To decode, all Color Buckets are initialized to empty sets.

First **b~0~** is encoded:

|===
| Type | Description | Condition | Effect

| nz_int_A(0,1) = 1
| Boolean: *nonempty*
|
|

| gnz_int_B(**orig_range(0).min**, **orig_range(0).max**)
| **min**
|
|

| gnz_int_C(**min**, **orig_range(0).max**)
| **max**
|
| if **max** - **min** < 2, then **b~0~** = { **min**, **max** }

| nz_int_D(0,1)
| **discrete**
| **max** - **min** > 1
| if **discrete** = 0, then **b~0~** = **min** .. **max**

| gnz_int_E(2, min(255, **max** - **min**))
| **n** = size of **b~0~**
| **discrete**
| **b~0~[0]** = **min**, **b~0~[n-1]** = **max** 

| gnz_int_F(**b~0~[_i_-1]**+1, **max** + 1 + **_i_** - **n**)
| **b~0~[_i_]**
| **discrete**, repeat: **_i_** from 1 to **n**-2
|
|===

Next, for all values **v~0~** in **b~0~**, Color Bucket **b~1~(v~0~)** is encoded:

|===
| Type | Description | Condition | Effect

| nz_int_A(0,1)
| Boolean: *nonempty*
|
| if false, **b~1~(v~0~)** is the empty set

| gnz_int_B(**orig_crange(1,v~0~).min**, **orig_crange(1,v~0~).max**)
| **min**
| *nonempty*
|

| gnz_int_C(**min**, **orig_range(1,v~0~).max**)
| **max**
| *nonempty*
| if **max** - **min** < 2, then **b~1~(v~0~)** = { **min**, **max** }

| nz_int_D(0,1)
| **discrete**
| **max** - **min** > 1
| if **discrete** = 0, then **b~1~(v~0~)** = **min** .. **max**

| gnz_int_E(2, min(510, **max** - **min**))
| **n** = size of **b~1~(v~0~)**
| **discrete**
| **b~1~(v~0~)[0]** = **min**, **b~1~(v~0~)[n-1]** = **max** 

| gnz_int_F(**b~1~(v~0~)[_i_-1]**+1, **max** + 1 + **_i_** - **n**)
| **b~1~(v~0~)[_i_]**
| **discrete**, repeat: **_i_** from 1 to **n**-2
|
|===


Next, for all values **v~0~** in **b~0~**, for all values **qv~1~** from 0 to (**orig_range(1).max** - **orig_range(1).min**) / 4, Color Bucket **b~2~(v~0~,qv~1~)** is encoded if for some _k_ in 0..3, it is the case that **v~1~** = **qv~1~** * 4 + **orig_range(1).min** + _k_ is in the set **b~1~(v~0~)**:

|===
| Type | Description | Condition | Effect

| nz_int_A(0,1)
| Boolean: *nonempty*
|
| if false, remove **v~1~** from **b~1~(v~0~)**

| gnz_int_B(min~k=0..3~(**orig_crange(2,v~0~,v~1~ + k).min**), max~k=0..3~(**orig_crange(2,v~0~,v~1~ + k).max**))
| **min**
| *nonempty*
|

| gnz_int_C(**min**, max~k=0..3~(**orig_crange(2,v~0~,v~1~ + k).max**))
| **max**
| *nonempty*
| if **max** - **min** < 2, then **b~2~(v~0~,qv~1~)** = { **min**, **max** }

| nz_int_D(0,1)
| **discrete**
| **max** - **min** > 1
| if **discrete** = 0, then **b~2~(v~0~,qv~1~)** = **min** .. **max**

| gnz_int_E(2, min(5, **max** - **min**))
| **n** = size of **b~2~(v~0~,qv~1~)**
| **discrete**
| **b~2~(v~0~,qv~1~)[0]** = **min**, **b~2~(v~0~,qv~1~)[n-1]** = **max** 

| gnz_int_F(**b~2~(v~0~,qv~1~)[_i_-1]**+1, **max** + 1 + **_i_** - **n**)
| **b~2~(v~0~,qv~1~)[_i_]**
| **discrete**, repeat: **_i_** from 1 to **n**-2
|
|===

Finally, if there is an Alpha channel (i.e. **nb_channels** > 3), then **b~3~** is encoded in exactly the same
way as **b~0~**.


[discrete]
=== Transformation 8: reserved (unused)
[discrete]
=== Transformation 9: reserved (unused)
=== Transformation 10: DuplicateFrame
=== Transformation 11: FrameShape
=== Transformation 12: FrameLookback
[discrete]
=== Transformation 13: reserved (unused)


